```{r}
library(devtools)
load_all()
```

# explanation of svd correction
## gsea result
```{r}
source("assist.R")
DeGsea = readRDS("../log/tcga_ccle_raw_svd_deg_gsea_kegg.rds")
p1 = Figure3_DrawGseaTable(DeGsea)
DeGsea = readRDS("../log/array_ccle_raw_svd_deg_gsea_kegg.rds")
p2 = Figure3_DrawGseaTable(DeGsea)
```

## immune score
```{r}
source("assist.R")
tcga_ccle = readRDS("../log/tcga_ccle.rds")
stromImm = readRDS("../log/tcga_ccle_raw_svd_stroImm.rds")
plot.res = Figure3_StromImmBox(stromImm, obj = tcga_ccle)
p3 = plot.res$blood_immune
p4 = plot.res$tissue_immune
```

```{r}
array_cell = readRDS("../log/array_ccle.rds")
stromImm = readRDS("../log/array_ccle_raw_svd_stroImm.rds")
plot.res = Figure3_StromImmBox(stromImm, obj = array_cell)
p5 = plot.res$blood_immune
p6 = plot.res$tissue_immune
```


# explanation of alignment
## cell classification
```{r}
source("assist.R")
tcga_cell_ann = tcga_ccle@pData@cell
seu_tcga = readRDS("../log/tcga_ccle_svd_seu.rds")
seu_id = stringr::str_replace_all(colnames(seu_tcga), "[.]", "-")
tcga_cell_ann$seu_cluster = seu_tcga@active.ident[match(tcga_cell_ann$sampleID, 
                                                         seu_id)]
tcga_cell_ann$mixture = seu_tcga@meta.data$seurat_clusters[match(tcga_cell_ann$sampleID, 
                                                         seu_id)]
tcga_cell_ann$mixture = ifelse(tcga_cell_ann$mixture %in% c("17", "11", "20", "16", "31", "54"), "mixture", "other")

p7 = Figure3_PlotCellClass(tcga_cell_ann)
```

```{r}
array_cell_ann = array_cell@pData@cell
seu_array = readRDS("../log/array_ccle_svd_seu.rds")
seu_id = stringr::str_replace_all(colnames(seu_array), "[.]", "-")
array_cell_ann$seu_cluster = seu_array@active.ident[match(array_cell_ann$sampleID, 
                                                         seu_id)]
p8 = Figure3_PlotCellClass(array_cell_ann, type="array")
```
## cell differentiation
```{r}
source("assist.R")
cell_trace.res = Fig3_CellTrace(obj = tcga_ccle, cell_ann = tcga_cell_ann)
p9 = cell_trace.res$DimDiff
p10 = cell_trace.res$mixture
p11 = cell_trace.res$matching
```
# arrangement
```{r}

pList1 = list( p7 = p7, p9 = p9, p1 = p1, p2 = p2)
gp1 = ggarrange(plotlist = pList1, ncol = 1, nrow = 4,
                labels = c("A", "C", "F", "G"),
                heights = c(2.5, 2, 1, 1))

pList2 = list(p11 = p11, p10 = p10,
              p3 = p3, p4 = p4,
              p5 = p5, p6 = p6 )

gp2 = ggarrange(plotlist = pList2, ncol = 2, nrow = 3,
                labels = c("D", "E", "H", "I", "J", "K"))

gp3 = ggarrange(p8, gp2, labels = c("B"), nrow = 2, heights = c(1, 3))
gp = ggarrange(gp1, gp3,
               widths = c(2, 1))
ggsave(gp, filename = "../log/figure3_explanation.pdf", width = 8, height = 11)
```

